version: 2

sources:

  - name: coffee_shop
    schema: coffee_shop
    project: analytics-engineers-club

    tables:
      - name: customers

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: name
          description: Name of the customer
          tests:
            - not_null
      
        - name: email 
          description: Email address of the customer

      - name: orders

        freshness:
          error_after:
            count: 1000
            period: day
        loaded_at_field: created_at    

        columns:
        - name: id
          description: Primary key of the model, order ID.
          test:
            - unique
            - not null

        - name: created_at
          description: Order creation datetime
          test:
            - not null
          
        - name: customer_id
          description: ID of the customer
          test:
            - not null

        - name: total

        - name: address
          description: The address of the customer
          test:
            - not null

        - name: state
          description: The state of the customer
          test:
            - not null
        
        - name: zip
          description: The zip code of the customer
          test: 
            - not null

      - name: order_items

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: order_id
          description: ID of the order the item is from
          tests:
            - not_null
      
        - name: product_id
          description: ID of the product this item corresponds to

      - name: products

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: name
          description: Name of the product
          tests:
            - not_null
      
        - name: category
          description: Category of the product
          tests:
            - not_null

        - name: created_at
          description: The date the product was created at
          test:
            - not_null

      - name: product_prices

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: product_id
          description: The ID of the product the price relates to
          tests:
            - not_null
      
        - name: price
          description: The price of the product at this time
          tests:
            - not_null

        - name: created_at
          description: The date the product price was valid from
          test:
            - not_null

        - name: ended_at
          description: The date the product price was valid until
          test:
            - not_null