version: 2

sources:

  - name: coffee_shop
    schema: coffee_shop
    project: analytics-engineers-club

    tables:
      - name: customers

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: name
          description: Name of the customer
          tests:
            - not_null
      
        - name: email 
          description: Email address of the customer

      - name: orders

        freshness:
          error_after:
            count: 1000
            period: day
        loaded_at_field: created_at    

        columns:
        - name: id
          description: Primary key of the model, order ID.
          tests:
            - unique
            - not_null

        - name: created_at
          description: Order creation datetime
          tests:
            - not_null
          
        - name: customer_id
          description: ID of the customer
          tests:
            - not_null

        - name: total

        - name: address
          description: The address of the customer
          tests:
            - not_null

        - name: state
          description: The state of the customer
          tests:
            - not_null
        
        - name: zip
          description: The zip code of the customer
          tests: 
            - not_null

      - name: order_items

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: order_id
          description: ID of the order the item is from
          tests:
            - not_null
      
        - name: product_id
          description: ID of the product this item corresponds to

      - name: products

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: name
          description: Name of the product
          tests:
            - not_null
      
        - name: category
          description: Category of the product
          tests:
            - not_null

        - name: created_at
          description: The date the product was created at
          tests:
            - not_null

      - name: product_prices

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - unique
            - not_null

        - name: product_id
          description: The ID of the product the price relates to
          tests:
            - not_null
      
        - name: price
          description: The price of the product at this time
          tests:
            - not_null

        - name: created_at
          description: The date the product price was valid from
          tests:
            - not_null

        - name: ended_at
          description: The date the product price was valid until
          tests:
            - not_null

  - name: web_tracking
    schema: web_tracking
    project: analytics-engineers-club

    tables:

      - name: pageviews

        columns:
        - name: id
          description: Primary key of the model
          tests:
            - not_null
            - unique

        - name: visitor_id
          description: ID of the visitor. One person may have several IDs dependent on the device they use etc.
          tests:
            - not_null
        
        - name: device_type
          description: Device type the visitor used
          tests:
            - not_null

        - name: timestamp
          description: Time the page view happened
          tests:
            - not_null
        
        - name: page
          description: The page visited
          tests:
            - not_null

        - name: customer_id
          description: The ID of the customer, if recognised. Null if not.

  - name: advanced_dbt_examples
    project: analytics-engineers-club

    tables:
    
      - name: form_events